spring.application.name=equitylens

spring.datasource.url=jdbc:postgresql://localhost:5432/equitylens
spring.datasource.username=equitylens
spring.datasource.password=equitylens_dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
